caravaggio2segrate/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('index/', include('index.urls')),
    path('admin/', admin.site.urls),
]

index/urls.py
from django.urls import path

from . import views

app_name = 'index'
urlpatterns = [
    path('', views.index, name='index'),
    path('checkavail/', views.checkavail, name='checkavail'),
]

index/models.py
from django.db import models

# Create your models here.


class CustomerData(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    address = models.CharField(max_length=250)
    city = models.CharField(max_length=50)
    nationality = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return self.surname

class BookingReference(models.Model):
    creationdate = models.DateTimeField(auto_now_add=True)
    lastmodifieddate = models.DateTimeField(auto_now=True)
    adultsnum = models.DecimalField(max_digits=1, decimal_places=0)
    kidsnum = models.DecimalField(max_digits=1, decimal_places=0)
    customerdata = models.ForeignKey(CustomerData, on_delete=models.CASCADE)

    def __str__(self):
        return self.creationdate.__str__()

class BookingCalendar(models.Model):
    ToBeConfirmed = 'TBC'
    Confirmed = 'CON'
    NotAvailable = 'N/A'
    BookingState = (
            (ToBeConfirmed, 'TO BE CONFIRMED'),
            (Confirmed, 'CONFIRMED'),
            (NotAvailable, 'NOT AVAILABLE'),
            )
    bookingdate = models.DateField(unique=True)
    bookingstate = models.CharField(max_length=3, choices=BookingState,
            default=ToBeConfirmed)
    bookingreference = models.ForeignKey(BookingReference, on_delete=models.CASCADE)

    def __str__(self):
        return self.bookingdate.__str__()

index/views.py
from django.shortcuts import render
import datetime

from .models import BookingCalendar

# Create your views here.

def index(request):
    return render(request, 'index/index.html')

def checkavail(request):
    checkinstr = request.POST['CheckIn']
    checkoutstr = request.POST['CheckOut']
    adultsstr = request.POST['Adults']
    kidsstr = request.POST['Kids']

    checkindate = datetime.date(int(checkinstr[4:8]), int(checkinstr[2:4]),
            int(checkinstr[:2]))
    checkoutdate = datetime.date(int(checkoutstr[4:8]), int(checkoutstr[2:4]),
            int(checkoutstr[:2]))

    daysnum = (checkoutdate - checkindate).days

    availability = {}
    booknow = True
    for day in range(daysnum):
        checkdate = checkindate + datetime.timedelta(day)
        filtdate = BookingCalendar.objects.filter(bookingdate=checkdate)
        if len(filtdate) == 0:
            checkresult = 'Available'
        else:
            checkresult = 'Not Available'
            booknow = False
        availability.update({checkdate.strftime('%d-%m-%Y'): checkresult})

    return render(request, 'index/checkavail.html', {
        'checkinstr': checkinstr,
        'checkoutstr': checkoutstr,
        'adultsstr': adultsstr,
        'kidsstr': kidsstr,
        'checkindate': checkindate.strftime('%d-%m-%Y'),
        'checkoutdate': checkoutdate.strftime('%d-%m-%Y'),
        'availability_list': sorted(availability.items()),
        'booknow': booknow,
        })

index/templates/index/base.html
<!DOCTYPE html>
<html lang="en">
    <head>

        <title>
            Caravaggio 2
        </title>

        <meta charset="UTF-8">
        <meta name="description" content="<Short Term Apartment Rental">
        <meta name="author=" content="Daniele Ceoldo">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet"
              href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css?family=Raleway">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <style>
            body,h1,h2,h3,h4,h5,h6 {
                font-family: "Raleway", Arial, Helvetica, sans-serif}
            .mySlides {display:none}
        </style>

    </head>

    <body class="w3-content w3-border-left w3-border-right">

        <!-- Sidebar/menu -->
        <nav class="w3-sidebar w3-light-grey w3-collapse w3-top" style="z-index:3;width:260px" id="mySidebar">
          <div class="w3-container w3-display-container w3-padding-16">
            <i onclick="w3_close()" class="fa fa-remove w3-hide-large w3-button w3-transparent w3-display-topright"></i>
            <h4>Short Term</h4>
            <h3>Apartment Rental</h3>
            <h3>from &euro;150 <span class="w3-medium">per night</span></h3>
            <hr>
            <form action="{% url 'index:checkavail' %}" method="post">
              {% csrf_token %}
              <p><label><i class="fa fa-calendar-check-o"></i> Check In</label></p>
              <input class="w3-input w3-border" 
                     type="text" placeholder="DD MM YYYY" 
                     {% block checkin_defval %}{% endblock %}
                     name="CheckIn" required>
              <p><label><i class="fa fa-calendar-o"></i> Check Out</label></p>
              <input class="w3-input w3-border"
                     type="text" placeholder="DD MM YYYY"
                     {% block checkout_defval %}{% endblock %}
                     name="CheckOut" required>
              <p><label><i class="fa fa-male"></i> Adults</label></p>
              <input class="w3-input w3-border"
                     type="number"
                     {% block adults_defval %}{% endblock %}
                     name="Adults" min="1" max="6">
              <p><label><i class="fa fa-child"></i> Kids</label></p>
              <input class="w3-input w3-border"
                     type="number"
                     {% block kids_defval %}{% endblock %}
                     name="Kids" min="0" max="6">
              <p><button class="w3-button w3-block w3-green w3-left-align"
                         type="submit">
                  <i class="fa fa-search w3-margin-right"></i> Check availability</button></p>
            </form>
          </div>
          <div class="w3-bar-block">
            <a href="#apartment" class="w3-bar-item w3-button w3-padding-16"><i class="fa fa-building"></i> Apartment</a>
            <a href="#contact-us" class="w3-bar-item w3-button w3-padding-16"><i class="fa fa-envelope"></i> Contact Us</a>
          </div>
        </nav>

        <!-- Top menu on small screens -->
        <header class="w3-bar w3-top w3-hide-large w3-black w3-xlarge">
          <span class="w3-bar-item">Rental</span>
          <a href="javascript:void(0)" class="w3-right w3-bar-item w3-button" onclick="w3_open()"><i class="fa fa-bars"></i></a>
        </header>

        <!-- Overlay effect when opening sidebar on small screens -->
        <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

        <!-- !PAGE CONTENT! -->
        <div class="w3-main w3-white" style="margin-left:260px">

          <!-- Push down content on small screens -->
          <div class="w3-hide-large" style="margin-top:80px"></div>

          <div class="w3-container" id="apartment">

              <h1 class="w3-text-green"style="margin-bottom: 48px;">
                  <a href="{% url 'index:index' %}" class="w3-button">
                  Caravaggio 2
                  </a>
              </h1>

{% block main_content %}

{% endblock main_content %}

          </div>

{% block additional_content %}

{% endblock additional_content %}

{% block contact_us %}

          <hr>

          <!-- Contact Us -->
          <div class="w3-container" id="contact-us">
            <h2>Contact Us</h2>
            <i class="fa fa-map-marker" style="width:30px"></i> Milan, Italy<br>
            <i class="fa fa-phone" style="width:30px"></i> Phone: +39 3283339894<br>
            <i class="fa fa-envelope" style="width:30px"> </i> Email: caravaggio2segrate@gmail.com<br>
            <p>Questions? Go ahead, ask them:</p>
            <form action="/action_page.php" target="_blank">
              <p><input class="w3-input w3-border" type="text" placeholder="Name" required name="Name"></p>
              <p><input class="w3-input w3-border" type="text" placeholder="Email" required name="Email"></p>
              <p><input class="w3-input w3-border" type="text" placeholder="Message" required name="Message"></p>
            <button type="submit" class="w3-button w3-green w3-third">Send a Message</button>
            </form>
          </div>

{% endblock contact_us %}

          <footer class="w3-container w3-padding-16" style="margin-top:32px">Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-text-green">w3.css</a></footer>

        <!-- End page content -->
        </div>

{% block script %}

{% endblock script %}

    </body>

</html>

index/templates/index/base_orig.html
<!DOCTYPE html>
<html lang="en">
    <head>

        <title>
            Caravaggio 2
        </title>

        <meta charset="UTF-8">
        <meta name="description" content="<Apartment Rental Web Site">
        <meta name="author=" content="Daniele Ceoldo">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet"
              href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css?family=Raleway">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <style>
            body,h1,h2,h3,h4,h5,h6 {
                font-family: "Raleway", Arial, Helvetica, sans-serif}
            .mySlides {display:none}
        </style>

    </head>

    <body class="w3-content w3-border-left w3-border-right">

        <!-- Sidebar/menu -->
        <nav class="w3-sidebar w3-light-grey w3-collapse w3-top" style="z-index:3;width:260px" id="mySidebar">
          <div class="w3-container w3-display-container w3-padding-16">
            <i onclick="w3_close()" class="fa fa-remove w3-hide-large w3-button w3-transparent w3-display-topright"></i>
            <h3>Rental</h3>
            <h3>from &euro;150</h3>
            <h6>per night</h6>
            <hr>
            <form action="{% url 'index:checkavail' %}" method="post">
              {% csrf_token %}
              <p><label><i class="fa fa-calendar-check-o"></i> Check In</label></p>
              <input class="w3-input w3-border" type="text" placeholder="DD MM YYYY" name="CheckIn" required>          
              <p><label><i class="fa fa-calendar-o"></i> Check Out</label></p>
              <input class="w3-input w3-border" type="text" placeholder="DD MM YYYY" name="CheckOut" required>         
              <p><label><i class="fa fa-male"></i> Adults</label></p>
              <input class="w3-input w3-border" type="number" value="1" name="Adults" min="1" max="6">              
              <p><label><i class="fa fa-child"></i> Kids</label></p>
              <input class="w3-input w3-border" type="number" value="0" name="Kids" min="0" max="6">
              <p><button class="w3-button w3-block w3-green w3-left-align" type="submit"><i class="fa fa-search w3-margin-right"></i> Search availability</button></p>
            </form>
          </div>
          <div class="w3-bar-block">
            <a href="#apartment" class="w3-bar-item w3-button w3-padding-16"><i class="fa fa-building"></i> Apartment</a>
            <a href="#contact" class="w3-bar-item w3-button w3-padding-16"><i class="fa fa-envelope"></i> Contact</a>
          </div>
        </nav>

        <!-- Top menu on small screens -->
        <header class="w3-bar w3-top w3-hide-large w3-black w3-xlarge">
          <span class="w3-bar-item">Rental</span>
          <a href="javascript:void(0)" class="w3-right w3-bar-item w3-button" onclick="w3_open()"><i class="fa fa-bars"></i></a>
        </header>

        <!-- Overlay effect when opening sidebar on small screens -->
        <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

        <!-- !PAGE CONTENT! -->
        <div class="w3-main w3-white" style="margin-left:260px">

          <!-- Push down content on small screens -->
          <div class="w3-hide-large" style="margin-top:80px"></div>

          <!-- Slideshow Header -->
          <div class="w3-container" id="apartment">
            <h2 class="w3-text-green">Caravaggio 2</h2>
            <div class="w3-display-container mySlides">
            <img src="/w3images/livingroom.jpg" style="width:100%;margin-bottom:-6px">
              <div class="w3-display-bottomleft w3-container w3-black">
                <p>Living Room</p>
              </div>
            </div>
            <div class="w3-display-container mySlides">
            <img src="/w3images/diningroom.jpg" style="width:100%;margin-bottom:-6px">
              <div class="w3-display-bottomleft w3-container w3-black">
                <p>Dining Room</p>
              </div>
            </div>
            <div class="w3-display-container mySlides">
            <img src="/w3images/bedroom.jpg" style="width:100%;margin-bottom:-6px">
              <div class="w3-display-bottomleft w3-container w3-black">
                <p>Bedroom</p>
              </div>
            </div>
            <div class="w3-display-container mySlides">
            <img src="/w3images/livingroom2.jpg" style="width:100%;margin-bottom:-6px">
              <div class="w3-display-bottomleft w3-container w3-black">
                <p>Living Room II</p>
              </div>
            </div>
            <div class="w3-display-container mySlides">
            <img src="/w3images/livingroom3.jpg" style="width:100%;margin-bottom:-6px">
              <div class="w3-display-bottomleft w3-container w3-black">
                <p>Living Room III</p>
              </div>
            </div>
            <div class="w3-display-container mySlides">
            <img src="/w3images/livingroom4.jpg" style="width:100%;margin-bottom:-6px">
              <div class="w3-display-bottomleft w3-container w3-black">
                <p>Living Room IV</p>
              </div>
            </div>
          </div>
          <div class="w3-row-padding w3-section">
            <div class="w3-col s3">
              <img class="demo w3-opacity w3-hover-opacity-off" src="/w3images/livingroom.jpg" style="width:100%;cursor:pointer" onclick="currentDiv(1)" title="Living room">
            </div>
            <div class="w3-col s3">
              <img class="demo w3-opacity w3-hover-opacity-off" src="/w3images/diningroom.jpg" style="width:100%;cursor:pointer" onclick="currentDiv(2)" title="Dining room">
            </div>
            <div class="w3-col s3">
              <img class="demo w3-opacity w3-hover-opacity-off" src="/w3images/bedroom.jpg" style="width:100%;cursor:pointer" onclick="currentDiv(3)" title="Bedroom">
            </div>
            <div class="w3-col s3">
              <img class="demo w3-opacity w3-hover-opacity-off" src="/w3images/livingroom2.jpg" style="width:100%;cursor:pointer" onclick="currentDiv(4)" title="Second Living Room">
            </div>
            <div class="w3-col s3">
              <img class="demo w3-opacity w3-hover-opacity-off" src="/w3images/livingroom3.jpg" style="width:100%;cursor:pointer" onclick="currentDiv(5)" title="Third Living Room">
            </div>
            <div class="w3-col s3">
              <img class="demo w3-opacity w3-hover-opacity-off" src="/w3images/livingroom4.jpg" style="width:100%;cursor:pointer" onclick="currentDiv(6)" title="Fourth Living Room">
            </div>
          </div>

          <div class="w3-container">
            <h4><strong>The space</strong></h4>
            <div class="w3-row w3-large">
              <div class="w3-col s6">
                <p><i class="fa fa-fw fa-male"></i> Max people: 4</p>
                <p><i class="fa fa-fw fa-bath"></i> Bathrooms: 2</p>
                <p><i class="fa fa-fw fa-bed"></i> Bedrooms: 1</p>
              </div>
              <div class="w3-col s6">
                <p><i class="fa fa-fw fa-clock-o"></i> Check In: After 3PM</p>
                <p><i class="fa fa-fw fa-clock-o"></i> Check Out: 12PM</p>
              </div>
            </div>
            <hr>
            
            <h4><strong>Amenities</strong></h4>
            <div class="w3-row w3-large">
              <div class="w3-col s6">
                <p><i class="fa fa-fw fa-shower"></i> Shower</p>
                <p><i class="fa fa-fw fa-wifi"></i> WiFi</p>
                <p><i class="fa fa-fw fa-tv"></i> TV</p>
              </div>
              <div class="w3-col s6">
                <p><i class="fa fa-fw fa-cutlery"></i> Kitchen</p>
                <p><i class="fa fa-fw fa-thermometer"></i> Heating</p>
                <p><i class="fa fa-fw fa-wheelchair"></i> Accessible</p>
              </div>
            </div>
            <hr>
            
            <h4><strong>Extra Info</strong></h4>
            <p>Our apartment is really clean and we like to keep it that way. Enjoy the lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            <p>We accept: <i class="fa fa-credit-card w3-large"></i> <i class="fa fa-cc-mastercard w3-large"></i> <i class="fa fa-cc-amex w3-large"></i> <i class="fa fa-cc-cc-visa w3-large"></i><i class="fa fa-cc-paypal w3-large"></i></p>
            <hr>
            
            <h4><strong>Rules</strong></h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          </div>
          <hr>
          
          <!-- Contact -->
          <div class="w3-container" id="contact">
            <h2>Contact</h2>
            <i class="fa fa-map-marker" style="width:30px"></i> Milan, Italy<br>
            <i class="fa fa-phone" style="width:30px"></i> Phone: +39 3283339894<br>
            <i class="fa fa-envelope" style="width:30px"> </i> Email: caravaggiosegrate@gmail.com<br>
            <p>Questions? Go ahead, ask them:</p>
            <form action="/action_page.php" target="_blank">
              <p><input class="w3-input w3-border" type="text" placeholder="Name" required name="Name"></p>
              <p><input class="w3-input w3-border" type="text" placeholder="Email" required name="Email"></p>
              <p><input class="w3-input w3-border" type="text" placeholder="Message" required name="Message"></p>
            <button type="submit" class="w3-button w3-green w3-third">Send a Message</button>
            </form>
          </div>
          
          <footer class="w3-container w3-padding-16" style="margin-top:32px">Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-text-green">w3.css</a></footer>

        <!-- End page content -->
        </div>

        <script>
        // Script to open and close sidebar when on tablets and phones
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
            document.getElementById("myOverlay").style.display = "block";
        }
         
        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
            document.getElementById("myOverlay").style.display = "none";
        }

        // Slideshow Apartment Images
        var slideIndex = 1;
        showDivs(slideIndex);

        function plusDivs(n) {
          showDivs(slideIndex += n);
        }

        function currentDiv(n) {
          showDivs(slideIndex = n);
        }

        function showDivs(n) {
          var i;
          var x = document.getElementsByClassName("mySlides");
          var dots = document.getElementsByClassName("demo");
          if (n > x.length) {slideIndex = 1}
          if (n < 1) {slideIndex = x.length}
          for (i = 0; i < x.length; i++) {
             x[i].style.display = "none";
          }
          for (i = 0; i < dots.length; i++) {
             dots[i].className = dots[i].className.replace(" w3-opacity-off", "");
          }
          x[slideIndex-1].style.display = "block";
          dots[slideIndex-1].className += " w3-opacity-off";
        }
        </script>

    </body>

</html>

index/templates/index/checkavail.html
{% extends "index/base.html" %}

{% block checkin_defval %}
    value="{{ checkinstr }}"
{% endblock %}

{% block checkout_defval %}
    value="{{ checkoutstr }}"
{% endblock %}

{% block adults_defval %}
    value="{{ adultsstr }}"
{% endblock %}

{% block kids_defval %}
    value="{{ kidsstr }}"
{% endblock %}


{% block main_content %}

              <!-- Availability  -->

              {% if booknow %}
              <div class="w3-padding-32 w3-large">
                <p>The requested dates:</p>
                <div class="w3-margin-top w3-margin-bottom">
                    <p>Check In: {{ checkindate }}</p>
                    <p>Check Out: {{ checkoutdate }}</p>
                </div>
                <p>are <b><i class="w3-bold">available!</i></b></p>
              </div>

              <form action="/action_page.php" target="_blank">
              <div class="w3-row" style="margin-bottom: 64px;">
                  <div class="w3-third">
                      <p></p>
                  </div>
                  <button type="submit" class="w3-button w3-green w3-third">
                      Book Now
                  </button>
              </div>
              </form>

              {% else %}

              {% for checkdate, checkresult in availability_list %}
                  <p>{{ checkdate }}: {{ checkresult }}</p>
              {% endfor %}

              {% endif %}

              <a href="{% url 'index:index' %}" class="w3-bar-item w3-button"><i class="fa fa-home w3-xlarge"></i><i class="fa fa-arrow-left w3-xlarge"></i></a>

{% endblock main_content %}

index/templates/index/index.html
{% extends "index/base.html" %}

{% block adults_defval %}
    value="1"
{% endblock %}

{% block kids_defval %}
    value="0"
{% endblock %}

{% block main_content %}

            <!-- Slideshow Header -->

            <div class="w3-display-container mySlides">
            <img src="/w3images/livingroom.jpg" style="width:100%;margin-bottom:-6px">
              <div class="w3-display-bottomleft w3-container w3-black">
                <p>Living Room</p>
              </div>
            </div>
            <div class="w3-display-container mySlides">
            <img src="/w3images/diningroom.jpg" style="width:100%;margin-bottom:-6px">
              <div class="w3-display-bottomleft w3-container w3-black">
                <p>Dining Room</p>
              </div>
            </div>
            <div class="w3-display-container mySlides">
            <img src="/w3images/bedroom.jpg" style="width:100%;margin-bottom:-6px">
              <div class="w3-display-bottomleft w3-container w3-black">
                <p>Bedroom</p>
              </div>
            </div>
            <div class="w3-display-container mySlides">
            <img src="/w3images/livingroom2.jpg" style="width:100%;margin-bottom:-6px">
              <div class="w3-display-bottomleft w3-container w3-black">
                <p>Living Room II</p>
              </div>
            </div>
            <div class="w3-display-container mySlides">
            <img src="/w3images/livingroom3.jpg" style="width:100%;margin-bottom:-6px">
              <div class="w3-display-bottomleft w3-container w3-black">
                <p>Living Room III</p>
              </div>
            </div>
            <div class="w3-display-container mySlides">
            <img src="/w3images/livingroom4.jpg" style="width:100%;margin-bottom:-6px">
              <div class="w3-display-bottomleft w3-container w3-black">
                <p>Living Room IV</p>
              </div>
            </div>

{% endblock main_content %}

{% block additional_content %}

          <div class="w3-row-padding w3-section">
            <div class="w3-col s3">
              <img class="demo w3-opacity w3-hover-opacity-off" src="/w3images/livingroom.jpg" style="width:100%;cursor:pointer" onclick="currentDiv(1)" title="Living room">
            </div>
            <div class="w3-col s3">
              <img class="demo w3-opacity w3-hover-opacity-off" src="/w3images/diningroom.jpg" style="width:100%;cursor:pointer" onclick="currentDiv(2)" title="Dining room">
            </div>
            <div class="w3-col s3">
              <img class="demo w3-opacity w3-hover-opacity-off" src="/w3images/bedroom.jpg" style="width:100%;cursor:pointer" onclick="currentDiv(3)" title="Bedroom">
            </div>
            <div class="w3-col s3">
              <img class="demo w3-opacity w3-hover-opacity-off" src="/w3images/livingroom2.jpg" style="width:100%;cursor:pointer" onclick="currentDiv(4)" title="Second Living Room">
            </div>
            <div class="w3-col s3">
              <img class="demo w3-opacity w3-hover-opacity-off" src="/w3images/livingroom3.jpg" style="width:100%;cursor:pointer" onclick="currentDiv(5)" title="Third Living Room">
            </div>
            <div class="w3-col s3">
              <img class="demo w3-opacity w3-hover-opacity-off" src="/w3images/livingroom4.jpg" style="width:100%;cursor:pointer" onclick="currentDiv(6)" title="Fourth Living Room">
            </div>
          </div>

          <div class="w3-container">
            <h4><strong>The space</strong></h4>
            <div class="w3-row w3-large">
              <div class="w3-col s6">
                <p><i class="fa fa-fw fa-male"></i> Max people: 4</p>
                <p><i class="fa fa-fw fa-bath"></i> Bathrooms: 2</p>
                <p><i class="fa fa-fw fa-bed"></i> Bedrooms: 1</p>
              </div>
              <div class="w3-col s6">
                <p><i class="fa fa-fw fa-clock-o"></i> Check In: After 3PM</p>
                <p><i class="fa fa-fw fa-clock-o"></i> Check Out: 12PM</p>
              </div>
            </div>
            <hr>
            
            <h4><strong>Amenities</strong></h4>
            <div class="w3-row w3-large">
              <div class="w3-col s6">
                <p><i class="fa fa-fw fa-shower"></i> Shower</p>
                <p><i class="fa fa-fw fa-wifi"></i> WiFi</p>
                <p><i class="fa fa-fw fa-tv"></i> TV</p>
              </div>
              <div class="w3-col s6">
                <p><i class="fa fa-fw fa-cutlery"></i> Kitchen</p>
                <p><i class="fa fa-fw fa-thermometer"></i> Heating</p>
                <p><i class="fa fa-fw fa-wheelchair"></i> Accessible</p>
              </div>
            </div>
            <hr>
            
            <h4><strong>Extra Info</strong></h4>
            <p>Our apartment is really clean and we like to keep it that way. Enjoy the lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            <p>We accept: <i class="fa fa-credit-card w3-large"></i> <i class="fa fa-cc-mastercard w3-large"></i> <i class="fa fa-cc-amex w3-large"></i> <i class="fa fa-cc-cc-visa w3-large"></i><i class="fa fa-cc-paypal w3-large"></i></p>
            <hr>
            
            <h4><strong>Rules</strong></h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          </div>

{% endblock additional_content %}

{% block script %}

        <script>
        // Script to open and close sidebar when on tablets and phones
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
            document.getElementById("myOverlay").style.display = "block";
        }
         
        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
            document.getElementById("myOverlay").style.display = "none";
        }

        // Slideshow Apartment Images
        var slideIndex = 1;
        showDivs(slideIndex);

        function plusDivs(n) {
          showDivs(slideIndex += n);
        }

        function currentDiv(n) {
          showDivs(slideIndex = n);
        }

        function showDivs(n) {
          var i;
          var x = document.getElementsByClassName("mySlides");
          var dots = document.getElementsByClassName("demo");
          if (n > x.length) {slideIndex = 1}
          if (n < 1) {slideIndex = x.length}
          for (i = 0; i < x.length; i++) {
             x[i].style.display = "none";
          }
          for (i = 0; i < dots.length; i++) {
             dots[i].className = dots[i].className.replace(" w3-opacity-off", "");
          }
          x[slideIndex-1].style.display = "block";
          dots[slideIndex-1].className += " w3-opacity-off";
        }
        </script>

{% endblock script %}